/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nilai_mahasiswa;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author LENOVO
 */
public class nilaiMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form nilaiMahasiswa
     */
    public nilaiMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nilaitugas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_kuis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nilaiuts = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nilaiuas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_keterangan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_nim = new javax.swing.JLabel();
        lbl_rerata = new javax.swing.JLabel();
        lbl_grade = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_hitung = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(":");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, -1));

        jLabel2.setText("NIM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(txt_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, -1));

        jLabel3.setText("Nilai Tugas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel1.add(txt_nilaitugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, -1));

        jLabel4.setText("Nilai Kuis");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel1.add(txt_kuis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, -1));

        jLabel5.setText("Nilai UTS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel1.add(txt_nilaiuts, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 150, -1));

        jLabel6.setText("Nilai UAS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        jPanel1.add(txt_nilaiuas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, -1));

        jLabel7.setText("Nama");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel8.setText("Keterangan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel9.setText(":");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 20, 20));

        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 20, 20));

        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 20, 20));

        jLabel12.setText(":");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 20, 20));

        lbl_keterangan.setText("-");
        jPanel1.add(lbl_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 130, 20));

        jLabel14.setText("NIM");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel15.setText("Rerata");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel16.setText("Grade");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel17.setText("Nama");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        lbl_nama.setText("-");
        jPanel1.add(lbl_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 130, 20));

        lbl_nim.setText("-");
        jPanel1.add(lbl_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 130, 20));

        lbl_rerata.setText("-");
        jPanel1.add(lbl_rerata, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 130, 20));

        lbl_grade.setText("-");
        jPanel1.add(lbl_grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 130, 20));

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        btn_hitung.setText("HITUNG");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        String nama;
        String nim;
        double nilaiTugas;
        double nilaiKuis;
        double nilaiUTS;
        double nilaiUAS;

        try {
            nama = txt_nama.getText();
            nim = txt_nim.getText();
            nilaiTugas = Double.parseDouble(txt_nilaitugas.getText());
            nilaiKuis = Double.parseDouble(txt_kuis.getText());
            nilaiUTS = Double.parseDouble(txt_nilaiuts.getText());
            nilaiUAS = Double.parseDouble(txt_nilaiuas.getText());
        } catch (NumberFormatException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Input nilai tidak valid");
            return;
        }
    double rerata = (nilaiTugas + nilaiKuis + nilaiUTS + nilaiUAS) / 4;
    
    char grade;
    if (rerata >= 85) {
        grade = 'A';
    } else if (rerata >= 70) {
        grade = 'B';
    } else if (rerata >= 55) {
        grade = 'C';
    } else if (rerata >= 40) {
        grade = 'D';
    } else {
        grade = 'E';
    }

    String keterangan = (rerata >= 55) ? "Lulus" : "Tidak Lulus";

    lbl_nama.setText(nama);
    lbl_nim.setText(nim);
    lbl_rerata.setText(String.valueOf(rerata));
    lbl_grade.setText(String.valueOf(grade));
    lbl_keterangan.setText(keterangan);
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
    txt_nama.setText("");
    txt_nim.setText("");
    txt_nilaitugas.setText("");
    txt_kuis.setText("");
    txt_nilaiuts.setText("");
    txt_nilaiuas.setText("");
    lbl_nama.setText("-");
    lbl_nim.setText("-");
    lbl_rerata.setText("-");
    lbl_grade.setText("-");
    lbl_keterangan.setText("-");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String nama;
        String nim;
        double nilaiTugas;
        double nilaiKuis;
        double nilaiUTS;
        double nilaiUAS;

        try {
            nama = txt_nama.getText();
            nim = txt_nim.getText();
            nilaiTugas = Double.parseDouble(txt_nilaitugas.getText());
            nilaiKuis = Double.parseDouble(txt_kuis.getText());
            nilaiUTS = Double.parseDouble(txt_nilaiuts.getText());
            nilaiUAS = Double.parseDouble(txt_nilaiuas.getText());
        } catch (NumberFormatException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Input nilai tidak valid");
            return;
        }
    double rerata = (nilaiTugas + nilaiKuis + nilaiUTS + nilaiUAS) / 4;
    char grade;
    if (rerata >= 85) {
        grade = 'A';
    } else if (rerata >= 70) {
        grade = 'B';
    } else if (rerata >= 55) {
        grade = 'C';
    } else if (rerata >= 40) {
        grade = 'D';
    } else {
        grade = 'E';
    }
    String keterangan = (rerata >= 55) ? "Lulus" : "Tidak Lulus";

    String url = "jdbc:mysql://localhost:3306/nilai_mahasiswa_db";
    String user = "root";
    String password = "";

    String query = "INSERT INTO nilai_mahasiswa (nama, nim, nilai_tugas, nilai_kuis, nilai_uts, nilai_uas, rerata, grade, keterangan) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try (Connection conn = DriverManager.getConnection(url, user, password);
         PreparedStatement pstmt = conn.prepareStatement(query)) {

        pstmt.setString(1, nama);
        pstmt.setString(2, nim);
        pstmt.setDouble(3, nilaiTugas);
        pstmt.setDouble(4, nilaiKuis);
        pstmt.setDouble(5, nilaiUTS);
        pstmt.setDouble(6, nilaiUAS);
        pstmt.setDouble(7, rerata);
        pstmt.setString(8, String.valueOf(grade));
        pstmt.setString(9, keterangan);

        pstmt.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
    }
    }//GEN-LAST:event_btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nilaiMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_grade;
    private javax.swing.JLabel lbl_keterangan;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nim;
    private javax.swing.JLabel lbl_rerata;
    private javax.swing.JTextField txt_kuis;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nilaitugas;
    private javax.swing.JTextField txt_nilaiuas;
    private javax.swing.JTextField txt_nilaiuts;
    private javax.swing.JTextField txt_nim;
    // End of variables declaration//GEN-END:variables
}
